---
title: "capstone"
author: "chang cong"
date: "2019/5/24"
output: html_document
---
```{r}
setwd("~/Desktop/ChangCongCapstone/dataset")
library(readr)
data <- read_csv("out.csv")
train <- read_csv("train.csv")
train<-train[,-1]

```
```{r}
#dependent variable
options(scipen=10)
summary(data$SalePrice)
hist(data$SalePrice,col = "#99CCFF", breaks=30,main = "Histogram of Sale Price",xlab="sale price") 
```

```{r}
par(mfrow=c(2,2))
hist(train$MoSold,col = "#99CCFF", breaks=5,main = "Histogram of Month Sold",xlab="month")
hist(train$YrSold,col = "#CCFFCC", breaks=5,main = "Histogram of Year Sold",xlab="year")
hist(train$YearBuilt,col = "#9999FF", breaks=20,main = "Histogram of Year Built",xlab="year")
hist(train$YearRemodAdd,col = "#FFCCCC", breaks=30,main = "Histogram of Year Remodel",xlab="year")
```

```{r}
par(mfrow=c(3,2))
hist(train$`1stFlrSF`,col = "#99CCFF", breaks=10,xlim=c(0,3000),main = "Histogram of First Floor Size",xlab="square feet")
hist(train$`2ndFlrSF`,col = "#99CCFF", breaks=10,main = "Histogram of Second Floor Size",xlab="square feet")
hist(train$LotArea,col = "#99CCFF", breaks=50,xlim=c(0,60000),main = "Histogram of Lot Basement Area Size",xlab="square feet")
hist(train$GarageArea,col = "#99CCFF", breaks=20,main = "Histogram of Garage Size",xlab="square feet")
hist(train$GrLivArea,col = "#99CCFF", breaks=15,main = "Histogram of Above Ground Living Area Size",xlab="square feet")
hist(train$BsmtFinSF1,col = "#99CCFF", breaks=20,xlim=c(0,3000),main = "Histogram of Type 1 Finished Area Size",xlab="square feet")
par(mfrow=c(3,2))
hist(train$BsmtUnfSF,col = "#99CCFF", breaks=5,xlim=c(0,3000),main = "Histogram of Unfinished Basement Area Size",xlab="square feet")
hist(train$TotalBsmtSF,col = "#99CCFF", breaks=20,xlim=c(0,4000),main = "Histogram of Basement Area Size",xlab="square feet")
hist(train$OpenPorchSF,col = "#99CCFF", breaks=10,main = "Histogram of Open Porch Area Size",xlab="square feet")
hist(train$WoodDeckSF,col = "#99CCFF", breaks=10,main = "Histogram of Wood deck Area Size",xlab="square feet")
hist(train$TotRmsAbvGrd,col = "#99CCFF", breaks=10,main = "Histogram of Number of Total Rooms",xlab="number of rooms")
```



```{r}
neighbor<-table(train$Neighborhood)
library("RColorBrewer")
display.brewer.all()
barplot(neighbor[order(neighbor,decreasing = FALSE)],space=1,horiz = TRUE,las=2, cex.names=0.8,col=brewer.pal(n=25,name = "Blues"),main = "Physical Locations Within Ames City Limits")
```

```{r}
ex1<-table(train$Exterior1st)
library("RColorBrewer")
display.brewer.all()
barplot(ex1[order(ex1,decreasing = FALSE)],space=1,horiz = TRUE,las=2, cex.names=1,col=brewer.pal(n=9,name = "Purples"),main = "Exterior Covering on House")
```


```{r}
over<-table(train$OverallQual)
library("RColorBrewer")
display.brewer.all()
barplot(over[order(over,decreasing = FALSE)],space=1,horiz = FALSE,las=2, cex.names=1,col=brewer.pal(n=9,name = "Oranges"),main = "Rates of the Overall Material and Finish of the house")
```

```{r}
library(car)
par(mfrow=c(4,5))
1<-scatterplot(SalePrice~MoSold,data=data)
2<-scatterplot(SalePrice~LotArea,data=data)
scatterplot(SalePrice~Neighborhood,data=data)
scatterplot(SalePrice~`1stFlrSF`,data=data)
scatterplot(SalePrice~`2ndFlrSF`,data=data)
scatterplot(SalePrice~BsmtUnfSF,data=data)
scatterplot(SalePrice~GarageArea,data=data)
scatterplot(SalePrice~GrLivArea,data=data)
scatterplot(SalePrice~YearRemodAdd,data=data)
scatterplot(SalePrice~YrSold,data=data)
scatterplot(SalePrice~YearBuilt,data=data)
scatterplot(SalePrice~TotalBsmtSF,data=data)
scatterplot(SalePrice~BsmtFinSF1,data=data)
scatterplot(SalePrice~TotRmsAbvGrd,data=data)
scatterplot(SalePrice~OpenPorchSF,data=data)
scatterplot(SalePrice~OverallQual,data=data)
scatterplot(SalePrice~WoodDeckSF,data=data)
scatterplot(SalePrice~Exterior2nd,data=data)
scatterplot(SalePrice~BsmtFinType1,data=data)
scatterplot(SalePrice~Exterior1st,data=data)

sp <- ggscatter(data, x = "MoSold", y = "SalePrice",
                add = "reg.line",               # Add regression line
                conf.int = TRUE)
sp1 <- ggscatter(data, x = "Neighborhood", y = "SalePrice",
                add = "reg.line",               # Add regression line
                conf.int = TRUE)
sp2 <- ggscatter(data, x = "LotArea", y = "SalePrice",
                add = "reg.line",               # Add regression line
                conf.int = TRUE)
ggarrange(sp, sp1,sp2+ rremove("x.text"), 
          labels = c("A", "B","C"),
          ncol = 2, nrow = 2)
```

